accounts/api/urls.py
from django.urls import path

from .views import UserListView, UserRetrieveUpdateDestroyView, registration

urlpatterns = [
    path('users/', UserListView.as_view(), name='api-user-list'),
    path('users/<int:pk>/', UserRetrieveUpdateDestroyView.as_view()),
    path('registration/', registration),
]

accounts/urls.py
from django.urls import path
from .views import UserDetailView, UserRegistrationView, UserLogoutView, UserLoginView


app_name = 'accounts'
urlpatterns = [
    path('sign-up/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(template_name='accounts/login_form.html'), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('me/', UserDetailView.as_view(), name='user-detail')
]

jobPortal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Job Project API",
      default_version='v1',
      description="Open source Job posting Portal",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include([
        path("", include("accounts.api.urls")),
        path("", include("jobs.api.urls")),
        path("", include("organizations.api.urls"))
    ])),
    path('api-auth/', include('rest_framework.urls')),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('jobs.urls')),

    # Swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

jobs/urls.py
from django.urls import path

from .views import JobCreateView, JobDetailView, JobListView, JobUpdateView, JobDeleteView, HomePageView

app_name = 'jobs'
urlpatterns = [
    path('jobs/<int:pk>/update/', JobUpdateView.as_view(), name='job-update'),
    path('jobs/<int:pk>/delete/', JobDeleteView.as_view(), name='job-delete'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('jobs/new/', JobCreateView.as_view(), name='job-create'),
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('', HomePageView.as_view(), name='homepage'),

]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(
        unique=True,
        blank=False,
        error_messages={
            "unique": _("Пользователь с таким email уже существует"),
        },
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    objects = UserManager()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ValidationError
from django.contrib.auth import authenticate
from django.utils.translation import ugettext_lazy as _

from .models import User


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Введите пароль',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']
        help_texts = {
            'email': None,
            'password1': None
        }
        error_messages = {
            'password_mismatch': 'Пароли не совпадают'
        }


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self, *args, **kwargs):
        cleaned_data = super(UserLoginForm, self).clean()

        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user is None:
                raise ValidationError(_('Пользователь с такими данными не существует!'))
            if not self.user.is_active:
                raise ValidationError(_('Данный аккаунт не активен'))
        return cleaned_data

    def get_user(self):
        return self.user

accounts/api/views.py
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView
from rest_framework import decorators
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from django.contrib.auth import get_user_model

from .serializers import UserSerializer, UserCreateSerializer

User = get_user_model()


@decorators.api_view(["POST"])
@decorators.permission_classes([permissions.AllowAny])
def registration(request):
    serializer = UserCreateSerializer(data=request.data)
    if not serializer.is_valid(raise_exception=True):
        return Response(serializer.errors, status.HTTP_400_BAD_REQUEST)
    else:
        user = serializer.save()
        print(user)
        res = {
            "status": True,
            "message": "Successfully registered",
        }
        return Response(res, status.HTTP_201_CREATED)


class UserListView(ListAPIView):
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAdminUser]
    queryset = User.objects.all()


class UserRetrieveUpdateDestroyView(RetrieveUpdateDestroyAPIView):
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAdminUser]
    queryset = User.objects.all()

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout, login
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, CreateView, RedirectView, FormView

from jobs.models import Job
from .forms import UserRegistrationForm, UserLoginForm

User = get_user_model()


class UserRegistrationView(CreateView):
    model = User
    template_name = 'accounts/registration.html'
    form_class = UserRegistrationForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect('/')
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password1')
            user.set_password(password)
            user.save()
            return redirect('accounts:login')
        else:
            return render(request, self.template_name, {'form': form})


class UserLoginView(FormView):
    form_class = UserLoginForm
    template_name = 'accounts/login_form.html'
    success_url = '/'
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(UserLoginView, self).dispatch(self.request, *args, **kwargs)

    def get_success_url(self):
        if "next" in self.request.GET and self.request.GET['next'] != "":
            return self.request.GET['next']
        else:
            return self.success_url

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class UserLogoutView(RedirectView):
    url = "/"

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(UserLogoutView, self).get(request, *args, **kwargs)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/account-detail.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['jobs'] = Job.objects.filter(creator=self.request.user)
        return context

    def get_object(self, queryset=None):
        return self.request.user

templates/accounts/account-detail.html
{% extends 'base.html' %}

{% block title %}
    Личный кабинет
{% endblock %}

{% block content %}
    <div class="spacer mt-5"></div>
    <section class="section">
        <div class="container">
            <div class="row">
                <h1 class="mb-4">Мои вакансии</h1>
                {% for job in jobs %}
                    <div class="col-md-12 jobs mb-3 bg-light border border-secondary">
                        <a href="{{ job.get_absolute_url }}" class="job-item p-1">
                            <div class="row">
                                <div class="col-md-3 job-item-company">
                                    <span class="text-secondary">Компания</span>
                                    <p class="font-weight-bold">{{ job.organization.name }}</p>
                                </div>
                                <div class="col-md-3 job-item-company">
                                    <span class="text-secondary">Позиция</span>
                                    <p class="font-weight-bold">{{ job.job_position }}</p>
                                </div>
                                <div class="col-md-3 job-item-salary">
                                    <span class="text-secondary">Оклад</span>
                                    {% if job.get_salary_info %}
                                        <p class="font-weight-bold">{{ job.get_salary_info }}</p>
                                    {% endif %}
                                </div>
                                <div class="col-md-3 job-item-salary">
                                    <span class="text-secondary">Тип</span>
                                    <p class="font-weight-bold">{{ job.get_type_display }}</p>
                                </div>
                            </div>
                        </a>
                        <div class="row pb-2">
                            <div class="col-md-4">
                                <a href="{{ job.get_absolute_url }}" class="btn btn-block btn-secondary">Посетить
                                    страницу</a>
                            </div>
                            <div class="col-md-4">
                                <a href="{% url 'jobs:job-update' job.id %}" class="btn btn-block btn-primary">Изменить
                                    настройки</a>
                            </div>
                            <div class="col-md-4">
                                <button type="button" class="btn btn-danger btn-block" data-toggle="modal"
                                        data-target="#exampleModalCenter">
                                    Удалить
                                </button>
                                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
                                     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongTitle">Удаление
                                                    вакансии</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <form action="{% url 'jobs:job-delete' job.pk %}" method="post">
                                                {% csrf_token %}
                                                <div class="modal-body">
                                                    Вы уверены что хотите удалить эту вакансию?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">Отмена
                                                    </button>
                                                    <button type="submit" class="btn btn-danger">Удалить</button>
                                                </div>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="col-md-12">
                    {% include 'includes/empty_list.html' %}
                    </div>

                {% endfor %}
            </div>

        </div>
    </section>
{% endblock %}

templates/accounts/login_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Войти
{% endblock %}

{% block content %}
    <div class="spacer pt-5"></div>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-9">
                 <h1 class="mb-3">Войти</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <button type="submit" class="btn btn-dark">Создать аккаунт</button>
                </form>

            </div>
        </div>

    </div>
{% endblock %}

templates/accounts/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Создать аккаунт
{% endblock %}

{% block content %}
    <div class="spacer pt-5"></div>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-9">
                 <h1 class="mb-3">Создать аккаунт</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <button type="submit" class="btn btn-dark">Войти</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}