accounts/urls.py
from django.urls import path
from .views import UserDetailView, UserRegistrationView, UserLogoutView, UserLoginView


app_name = 'accounts'
urlpatterns = [
    path('sign-up/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(template_name='accounts/login_form.html'), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('me/', UserDetailView.as_view(), name='user-detail')
]

jobPortal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Job Project API",
      default_version='v1',
      description="Open source Job posting Portal",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include([
        path("", include("accounts.api.urls")),
        path("", include("jobs.api.urls")),
        path("", include("organizations.api.urls"))
    ])),
    path('api-auth/', include('rest_framework.urls')),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('jobs.urls')),

    # Swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

jobs/urls.py
from django.urls import path

from .views import JobCreateView, JobDetailView, JobListView, JobUpdateView, JobDeleteView, HomePageView

app_name = 'jobs'
urlpatterns = [
    path('jobs/<int:pk>/update/', JobUpdateView.as_view(), name='job-update'),
    path('jobs/<int:pk>/delete/', JobDeleteView.as_view(), name='job-delete'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('jobs/new/', JobCreateView.as_view(), name='job-create'),
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('', HomePageView.as_view(), name='homepage'),

]

organizations/urls.py
from django.urls import path

from .views import OrganizationListView, OrganizationCreateView, OrganizationDetailView

app_name = 'organizations'
urlpatterns = [
    path('<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('new/', OrganizationCreateView.as_view(), name='organization-create'),
    path('', OrganizationListView.as_view(), name='organization-list'),
]

templates/includes/_header.html
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row navbar-sticky navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Developers Today</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'jobs:job-list' %}">Последние вакансии <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'organizations:organization-list' %}">Организации</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-danger">Выйти</a></li>
                    <li class="nav-item"> <a href="{% url 'accounts:user-detail' %}" class="nav-link">Кабинет</a></li>
                    {% else %}
                    <li class="nav-item mr-4"><a href="{% url 'accounts:registration' %}" class="btn btn-primary">Создать аккаунт</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:login' %}" class="btn btn-primary">Войти</a></li>
                    {% endif %}

            </ul>

        </div>
    </div>
</header>

templates/includes/empty_list.html
<div class="wrapper rounded border border-info bg-light d-flex justify-content-md-center align-items-center" style="min-height: 350px;">
    <div class="content p-5 text-center">
        <h4 class="font-weight-bold pb-3">Тут пока что ничего нет</h4>
        <a href="{% url 'homepage' %}" class="btn btn-info">Перейти на главную страницу</a></div>
</div>