jobPortal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Job Project API",
      default_version='v1',
      description="Open source Job posting Portal",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include([
        path("", include("accounts.api.urls")),
        path("", include("jobs.api.urls")),
        path("", include("organizations.api.urls"))
    ])),
    path('api-auth/', include('rest_framework.urls')),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('jobs.urls')),

    # Swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

jobs/api/urls.py
from django.urls import path

from .views import JobDetailView, JobListView, ApiRootView

urlpatterns = [
    path('', ApiRootView.as_view(), name='api-root'),
    path('jobs/', JobListView.as_view(), name='api-job-list'),
    path('jobs/<int:pk>/', JobDetailView.as_view())
]

jobs/urls.py
from django.urls import path

from .views import JobCreateView, JobDetailView, JobListView, JobUpdateView, JobDeleteView, HomePageView

app_name = 'jobs'
urlpatterns = [
    path('jobs/<int:pk>/update/', JobUpdateView.as_view(), name='job-update'),
    path('jobs/<int:pk>/delete/', JobDeleteView.as_view(), name='job-delete'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('jobs/new/', JobCreateView.as_view(), name='job-create'),
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('', HomePageView.as_view(), name='homepage'),

]

jobs/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


class Job(models.Model):
    TYPE_CHOICES = (
        ('office', _('Работа в офисе')),
        ('project', _('Разовая работа над проектом')),
        ('remote', _('Удаленная работа')),
        ('internship', _('Стажировка'))
    )

    SALARY_CHOICES = (
        ('monthly', _('Месячный оклад')),
        ('hourly', _('Почасовая оплата')),
        ('fixed', _('Фиксированная'))
    )

    CURRENCY_CHOICES = (
        ('KGS', 'KGS'),
        ('USD', 'USD'),
        ('EURO', 'EURO'),
        ('RUB', 'RUB')
    )

    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='jobs',
        verbose_name=_('Вакансия')
    )
    organization = models.ForeignKey(
        'organizations.Organization',
        on_delete=models.CASCADE,
        related_name='jobs',
        verbose_name=_('Организация')
    )
    job_position = models.CharField(max_length=100, verbose_name=_('Должность'))
    description = models.TextField(verbose_name=_('Описание работы'))
    telegram = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Telegram'))
    email = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('E-mail'))
    phone = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Номер телефона'))
    type = models.CharField(max_length=30, choices=TYPE_CHOICES, verbose_name=_('Тип работы'))
    salary = models.CharField(max_length=30, choices=SALARY_CHOICES, verbose_name=_('Оклад'))
    salary_min = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('Минимальная зарплата'))
    salary_max = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('Максимальная зарплата'))
    currency = models.CharField(max_length=4,
                                choices=CURRENCY_CHOICES,
                                null=True,
                                blank=True,
                                verbose_name=_('Валюта'))
    city = models.CharField(max_length=100,
                            null=True,
                            blank=True,
                            verbose_name=_('Город'))
    is_expired = models.BooleanField(blank=True, default=False, verbose_name=_('Актуальность'))
    is_approved = models.BooleanField(blank=True, default=True, verbose_name=_('Подтвердить'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at', 'updated_at']
        verbose_name = _('Вакансия')
        verbose_name_plural = _('Вакансии')

    def __str__(self):
        return self.job_position

    def get_absolute_url(self):
        return reverse('jobs:job-detail', args=[self.pk])

    def get_salary_info(self):
        if self.salary_max and self.salary_min:
            return "%s-%s %s" % (self.salary_min, self.salary_max, self.get_currency_display())
        else:
            return _("Не указано")

    def get_job_type(self):
        if self.type == 'remote':
            return self.get_type_display()
        else:
            return "%s/%s" % (self.get_type_display(), self.city)

jobs/forms.py
from django import forms
from django.forms import ValidationError
from .models import Job


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('creator', 'is_expired', 'is_approved')

    def clean(self):
        cleaned_data = super(JobForm, self).clean()
        telegram = cleaned_data.get('telegram')
        phone = cleaned_data.get('phone')
        email = cleaned_data.get('email')
        if not telegram and not email and not phone:
            raise ValidationError('Укажите контактные данные для отклика')
        return cleaned_data

    def clean_city(self):
        job_type = self.cleaned_data.get('type')
        city = self.cleaned_data.get('city')
        if job_type != 'remote' and city is None:
            raise ValidationError('Укажите город')
        return city

    def clean_salary_max(self):
        min_salary = self.cleaned_data.get('salary_min')
        max_salary = self.cleaned_data.get('salary_max')

        if (min_salary and not max_salary) or (max_salary and not min_salary):
            raise ValidationError('Укажите максимальную и минимальную зарплату')
        if int(min_salary) > int(max_salary):
            raise ValidationError('Максимальная зарплата не может быть меньше минимальной')
        return max_salary

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if len(description) < 100:
            raise ValidationError('Описание должно содержать минимум 100 символов')
        return description

jobs/api/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework import permissions
from rest_framework import authentication
from rest_framework.reverse import reverse
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import filters

from .serializers import JobSerializer
from jobs.models import Job
from .permissions import IsCreatorOrReadOnly


class ApiRootView(APIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get(self, request):
        return Response({
            'user-list': reverse('api-user-list', request=request),
            'organization-list': reverse('api-organization-list', request=request),
            'job-list': reverse('api-job-list', request=request)
        })


class JobListView(ListCreateAPIView):
    serializer_class = JobSerializer
    queryset = Job.objects.all()
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    authentication_classes = [authentication.SessionAuthentication]
    filter_backends = [filters.OrderingFilter, filters.SearchFilter]

    ordering_fields = ['job_position', 'created_at', 'is_expired', 'salary_min']
    ordering = ['job_position']
    search_fields = ['job_position']


    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)


class JobDetailView(RetrieveUpdateDestroyAPIView):
    serializer_class = JobSerializer
    queryset = Job.objects.all()
    permission_classes = [IsCreatorOrReadOnly, permissions.IsAuthenticatedOrReadOnly]

jobs/views.py
from django.urls import reverse_lazy, reverse
from django.http import Http404, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import JobForm
from .models import Job
from organizations.models import Organization


class HomePageView(ListView):
    model = Job
    template_name = 'homepage.html'
    paginate_by = 7

    def get_queryset(self):
        return Job.objects.filter(is_approved=True)


class JobCreateView(LoginRequiredMixin, CreateView):
    model = Job
    form_class = JobForm
    template_name = 'jobs/job_create_form.html'
    success_url = reverse_lazy('jobs:job-detail')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('jobs:job-detail', args=[self.object.pk])


class JobDetailView(DetailView):
    model = Job
    template_name = 'jobs/job_detail.html'
    context_object_name = 'job'

    def get_context_data(self, **kwargs):
        context = super(JobDetailView, self).get_context_data(**kwargs)
        job = self.get_object()
        organization = Organization.objects.get(id=job.organization.id)
        context['organization'] = organization
        return context


class JobUpdateView(LoginRequiredMixin, UpdateView):
    model = Job
    form_class = JobForm
    template_name = 'jobs/job_update.html'
    success_url = reverse_lazy('user-detail')

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().creator != request.user:
            raise Http404
        return super(JobUpdateView, self).dispatch(self.request, *args, **kwargs)


class JobDeleteView(LoginRequiredMixin, DeleteView):
    model = Job
    success_url = reverse_lazy('user-detail')

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().creator != request.user:
            raise Http404
        return super(JobDeleteView, self).dispatch(self.request, *args, **kwargs)


class JobListView(ListView):
    model = Job
    template_name = 'jobs/job_list.html'
    context_object_name = 'jobs'
    paginate_by = 10

    def get_queryset(self):
        return Job.objects.filter(is_approved=True)

templates/jobs/job_create_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Добавить вакансию
{% endblock %}

{% block content %}
    <div class="spacer pt-5"></div>
    <section>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-9">
                 <h1 class="mb-3">Добавить новую вакансию</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark">Сохранить</button>
                </form>
            </div>
        </div>

    </div>
    </section>

{% endblock %}

templates/jobs/job_detail.html
{% extends 'base.html' %}

{% block title %}
{{ job.job_position }}
{% endblock %}

{% block content %}
    <div class="spacer pt-5"></div>
    <section class="job-detail">
        <div class="container">
            <h1>{{ job.job_position }}</h1>
            <div class="row mb-3 mt-3">
                <div class="col-md-12">
                    <div class="company-detail bg-light border border-secondary p-2">
                        <a href="{{ organization.get_absolute_url }}" class="">
                            <span class="text-secondary">Организация</span>
                            <p class="">{{ organization.name }}</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <div class="job-information mt-4 mb-4">
                        <div class="job-salary">
                            <span class="text-secondary">Оклад</span>
                            <p class="font-weight-bold">{{ job.get_salary_info }}</p>
                        </div>
                        <div class="job-type">
                            <span class="text-secondary">Тип работы</span>
                            <p class="font-weight-bold">{{ job.get_job_type }}</p>
                        </div>

                    </div>
                    <div class="spacer mt-3"></div>
                     <div class="job-description bg-light p-4" style="min-height: 400px;">
                         <p>{{ job.description }}</p>
                     </div>
                    <div class="job-contacts">
                        {% if job.telegram %}
                        <p>Telegram: <a href="">{{ job.telegram }}</a></p>
                        {% endif %}
                        {% if job.phone %}
                        <p>Телефон: <a href="">{{ job.phone }}</a></p>
                        {% endif %}
                        {% if job.email %}
                        <p>E-mail: <a href="">{{ job.email }}</a></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </section>
{% endblock %}

templates/jobs/job_list.html
{% extends 'base.html' %}


{% block title %}
    Последние вакансии
{% endblock %}

{% block content %}
    <div class="spacer mt-5"></div>
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="offset-md-8 col-md-4 text-right">
                    <a href="{% url 'jobs:job-create' %}" class="btn btn-outline-success">Добавить вакансию</a>
                </div>
            </div>
        <div class="spacer mt-3"></div>
            <div class="row">
                {% for job in jobs %}
                    <div class="col-md-12 jobs mb-3 bg-light border border-secondary">
                        <a href="{{ job.get_absolute_url }}" class="job-item p-1">
                            <div class="row">
                                <div class="col-md-3 job-item-company">
                                    <span class="text-secondary">Компания</span>
                                    <p class="font-weight-bold">{{ job.organization.name }}</p>
                                </div>
                                <div class="col-md-3 job-item-company">
                                    <span class="text-secondary">Позиция</span>
                                    <p class="font-weight-bold">{{ job.job_position }}</p>
                                </div>
                                <div class="col-md-3 job-item-salary">
                                    <span class="text-secondary">Оклад</span>
                                    {% if job.get_salary_info %}
                                        <p class="font-weight-bold">{{ job.get_salary_info }}</p>
                                    {% endif %}
                                </div>
                                <div class="col-md-3 job-item-salary">
                                    <span class="text-secondary">Тип</span>
                                    <p class="font-weight-bold">{{ job.get_type_display }}</p>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% empty %}
                    <div class="col-md-12">
                        {% include 'includes/empty_list.html' %}
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>
{% endblock content %}

templates/jobs/job_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Изменить данные
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-9">
                 <h1 class="mb-3">Изменить данные вакансии</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark">Сохранить</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}