jobPortal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Job Project API",
      default_version='v1',
      description="Open source Job posting Portal",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include([
        path("", include("accounts.api.urls")),
        path("", include("jobs.api.urls")),
        path("", include("organizations.api.urls"))
    ])),
    path('api-auth/', include('rest_framework.urls')),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('jobs.urls')),

    # Swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

jobs/urls.py
from django.urls import path

from .views import JobCreateView, JobDetailView, JobListView, JobUpdateView, JobDeleteView, HomePageView

app_name = 'jobs'
urlpatterns = [
    path('jobs/<int:pk>/update/', JobUpdateView.as_view(), name='job-update'),
    path('jobs/<int:pk>/delete/', JobDeleteView.as_view(), name='job-delete'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('jobs/new/', JobCreateView.as_view(), name='job-create'),
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('', HomePageView.as_view(), name='homepage'),

]

organizations/api/urls.py
from django.urls import path

from .views import OrganizationListView, OrganizationDetailView

urlpatterns = [
    path("organizations/", OrganizationListView.as_view(), name='api-organization-list'),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view())
]

organizations/urls.py
from django.urls import path

from .views import OrganizationListView, OrganizationCreateView, OrganizationDetailView

app_name = 'organizations'
urlpatterns = [
    path('<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('new/', OrganizationCreateView.as_view(), name='organization-create'),
    path('', OrganizationListView.as_view(), name='organization-list'),
]

organizations/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from jobs.models import Job


class Organization(models.Model):
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='organizations',
        verbose_name=_('Создатель')
    )
    logo = models.ImageField(
        upload_to='logos/%Y/%m/%d',
        blank=True,
        null=True,
        verbose_name=_('Логотип')
    )
    name = models.CharField(max_length=120, unique=True, verbose_name=_('Название'))
    description = models.TextField(verbose_name=_('Описание'))
    website = models.URLField(null=True, blank=True, verbose_name=_('Веб-сайт'))

    class Meta:
        ordering = ['id', 'name']
        verbose_name = _('Организация')
        verbose_name_plural = _('Организации')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizations:organization-detail', args=[self.id])

    def get_jobs_count(self):
        return Job.objects.filter(organization_id=self.id, is_approved=True).count()

organizations/forms.py
from django import forms
from django.forms import ValidationError

from .models import Organization


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['logo', 'name', 'description', 'website']

organizations/api/views.py
from rest_framework import permissions
from rest_framework import authentication
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework import filters

from organizations.models import Organization
from .serializers import OrganizationSerializer
from jobs.api.permissions import IsCreatorOrReadOnly


class OrganizationListView(ListCreateAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    authentication_classes = [authentication.SessionAuthentication]

    filter_backends = [filters.OrderingFilter, filters.SearchFilter]
    ordering_fields = ['name', 'id']
    ordering = ['name']
    search_fields = ['name']

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)


class OrganizationDetailView(RetrieveUpdateDestroyAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationSerializer
    permission_classes = [IsCreatorOrReadOnly, permissions.IsAuthenticatedOrReadOnly]
    authentication_classes = [authentication.SessionAuthentication]

organizations/views.py
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from .models import Organization
from .forms import OrganizationForm
from jobs.models import Job


class OrganizationListView(ListView):
    model = Organization
    template_name = 'organizations/organization_list.html'
    context_object_name = 'organizations'
    paginate_by = 10


class OrganizationDetailView(DetailView):
    model = Organization
    template_name = 'organizations/organization_detail.html'
    context_object_name = 'organization'

    def get_context_data(self, **kwargs):
        organization = self.get_object()
        context = super(OrganizationDetailView, self).get_context_data(**kwargs)
        context['jobs'] = Job.objects.filter(organization=organization, is_approved=True)
        return context


class OrganizationCreateView(LoginRequiredMixin, CreateView):
    model = Organization
    template_name = 'organizations/organization_form.html'
    form_class = OrganizationForm

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(OrganizationCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('organizations:organization-detail', args=[self.object.pk])

templates/organizations/organization_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ organization.name }}
{% endblock %}

{% block content %}
    <div class="spacer mt-5"></div>
    <section class="job-detail">
        <div class="container">
            <h1>{{ organization.name }}</h1>
            <div class="row">
                <div class="col-md-9">
                    <div class="job-information mt-4 mb-4">
                        <div class="job-salary">
                            {% if organization.website %}
                                <span class="text-secondary">Веб-сайт</span>
                                <p>
                                    <a href="{{ organization.website }}" target="_blank"
                                       class="font-weight-bold">{{ organization.website }}</a>
                                </p>
                            {% endif %}
                        </div>

                    </div>
                    <div class="spacer mt-5"></div>
                    <p class="text-secondary font-weight-bold">Информация о компании</p>
                    <div class="job-description bg-light p-4" style="min-height: 300px;">
                        <p>{{ organization.description }}</p>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </section>
    <div class="spacer mt-5"></div>
    <section>
        <div class="container">
            <h4 class="text-secondary mb-3">Вакансии</h4>
            {% for job in jobs %}
                <a href="{{ job.get_absolute_url }}" class="row bg-light mb-3">
                    <div class="col-md-12 p-3">
                        <div class="row">
                            <div class="col-md-3 job-item-company">
                                <span class="text-secondary">Компания</span>
                                <p class="font-weight-bold">{{ job.organization.name }}</p>
                            </div>
                            <div class="col-md-3 job-item-company">
                                <span class="text-secondary">Позиция</span>
                                <p class="font-weight-bold">{{ job.job_position }}</p>
                            </div>
                            <div class="col-md-3 job-item-salary">
                                <span class="text-secondary">Оклад</span>
                                {% if job.get_salary_info %}
                                    <p class="font-weight-bold">{{ job.get_salary_info }}</p>
                                {% endif %}
                            </div>
                            <div class="col-md-3 job-item-salary">
                                <span class="text-secondary">Тип</span>
                                <p class="font-weight-bold">{{ job.get_type_display }}</p>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/organizations/organization_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Добавить вакансию
{% endblock %}

{% block content %}
    <div class="spacer pt-5"></div>
    <section>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-9">
                 <h1 class="mb-3">Добавить организацию</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-dark">Сохранить</button>
                </form>
            </div>
        </div>

    </div>
    </section>

{% endblock %}

templates/organizations/organization_list.html
{% extends 'base.html' %}


{% block title %}
    Последние вакансии
{% endblock %}

{% block content %}
    <style>
        .job-item:hover {
            text-decoration: none !important;
        }
    </style>
    <div class="spacer mt-5"></div>
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 offset-md-9 text-right">
                    <a href="{% url 'organizations:organization-create' %}" class="btn btn-outline-success">Добавить
                    организацию</a></div>
            </div>
            <div class="spacer mt-3"></div>
            <div class="row">
                {% for organization in organizations %}
                    <div class="col-md-12 jobs mb-3 bg-light border border-secondary">
                        <a href="{{ organization.get_absolute_url }}" class="job-item p-1">
                            <div class="row">
                                <div class="col-md-9 job-item-company">
                                    <span class="text-secondary">Компания</span>
                                    <p class="font-weight-bold">{{ organization.name }}</p>
                                </div>
                                <div class="col-md-3 job-item-salary text-center">
                                    <span class="text-secondary">Вакансий</span>
                                    <p class="font-weight-bold">{{ organization.get_jobs_count }}</p>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% empty %}
                    <div class="col-md-12">
                        {% include 'includes/empty_list.html' %}
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>
{% endblock content %}